# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detailsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os
import json

KNOWN_FACE_DIR = "img/known"
DATA_DIR = "data"

class Ui_detailsWindow(object):

    def __init__(self,message):
        print("Passed Data: "+message)
        self.message = message
    def assignValues(self):

            criminalImagePath = f"{KNOWN_FACE_DIR}/{self.message}"
            pixmap = QPixmap(criminalImagePath)
            self.criminalImageLabel.setPixmap(QPixmap(pixmap))

            self.CId=os.path.splitext(self.message)[0]
            self.criminalIDLabel.setText(self.CId)

            with open(f"{DATA_DIR}/{self.CId}/allData.json") as json_file:
                    data = json.load(json_file)
                    criminalName = data['name']
                    criminalAddress = data['address']
                    criminalContact = data['contact']
                    criminalAge = data['age']
                    criminalGender = data['gender']
                    criminalCases = data['cases']

            self.nameLabel.setText(criminalName)
            self.addressLabel.setText(criminalAddress)
            self.ageAndGenderLabel.setText(str(criminalAge) + " years old " + criminalGender)
            self.contactDetailsLabel.setText(criminalContact)
            self.casesLabel.setText(criminalCases)

    def setupUi(self, detailsWindow):
        detailsWindow.setObjectName("detailsWindow")
        detailsWindow.resize(500, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(detailsWindow.sizePolicy().hasHeightForWidth())
        detailsWindow.setSizePolicy(sizePolicy)
        detailsWindow.setMinimumSize(QtCore.QSize(500, 500))
        detailsWindow.setMaximumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        detailsWindow.setWindowIcon(icon)
        detailsWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(detailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticaBlFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticaBlFrame.setGeometry(QtCore.QRect(0, 0, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticaBlFrame.sizePolicy().hasHeightForWidth())
        self.verticaBlFrame.setSizePolicy(sizePolicy)
        self.verticaBlFrame.setMinimumSize(QtCore.QSize(500, 500))
        self.verticaBlFrame.setMaximumSize(QtCore.QSize(500, 500))
        self.verticaBlFrame.setStyleSheet("background-color: rgb(130, 157, 255);\n"
"border: 1px solid rgb(130,157,240);")
        self.verticaBlFrame.setObjectName("verticaBlFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticaBlFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.criminalImageLabel = QtWidgets.QLabel(self.verticaBlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.criminalImageLabel.sizePolicy().hasHeightForWidth())
        self.criminalImageLabel.setSizePolicy(sizePolicy)
        self.criminalImageLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.criminalImageLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.criminalImageLabel.setStyleSheet("border: 1px solid rgb(88, 73, 255);\n"
"border-radius: 4px;")
        self.criminalImageLabel.setText("")
        self.criminalImageLabel.setPixmap(QtGui.QPixmap(":/newPrefix/baseManIcon.png"))
        self.criminalImageLabel.setScaledContents(True)
        self.criminalImageLabel.setObjectName("criminalImageLabel")
        self.verticalLayout.addWidget(self.criminalImageLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.verticaBlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_2.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_2.setSizePolicy(sizePolicy)
        self.horizontalFrame_2.setMinimumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_2.setStyleSheet("border-radius: 6px;")
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 25))
        self.label_2.setMaximumSize(QtCore.QSize(100, 25))
        self.label_2.setStyleSheet("background-color: rgb(51, 51, 255);\n"
"color: rgb(255,255,255);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.nameLabel = QtWidgets.QLabel(self.horizontalFrame_2)
        self.nameLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.nameLabel.setMaximumSize(QtCore.QSize(400, 25))
        self.nameLabel.setStyleSheet("border: 1px solid rgb(88, 73, 255);\n"
"background-color: rgb(216, 227, 255);")
        self.nameLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_3.addWidget(self.nameLabel)
        self.verticalLayout.addWidget(self.horizontalFrame_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalFrame_4 = QtWidgets.QFrame(self.verticaBlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_4.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_4.setSizePolicy(sizePolicy)
        self.horizontalFrame_4.setMinimumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_4.setMaximumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_4.setStyleSheet("border-radius: 6px;")
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 25))
        self.label_3.setMaximumSize(QtCore.QSize(100, 25))
        self.label_3.setStyleSheet("background-color: rgb(51, 51, 255);\n"
"color: rgb(255,255,255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.criminalIDLabel = QtWidgets.QLabel(self.horizontalFrame_4)
        self.criminalIDLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.criminalIDLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.criminalIDLabel.setStyleSheet("border: 1px solid rgb(88, 73, 255);\n"
"background-color: rgb(216, 227, 255);")
        self.criminalIDLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.criminalIDLabel.setObjectName("criminalIDLabel")
        self.horizontalLayout_5.addWidget(self.criminalIDLabel)
        self.verticalLayout.addWidget(self.horizontalFrame_4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalFrame_3 = QtWidgets.QFrame(self.verticaBlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_3.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_3.setSizePolicy(sizePolicy)
        self.horizontalFrame_3.setMinimumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_3.setMaximumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_3.setStyleSheet("border-radius: 6px;")
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 25))
        self.label_4.setMaximumSize(QtCore.QSize(100, 25))
        self.label_4.setStyleSheet("background-color: rgb(51, 51, 255);\n"
"color: rgb(255,255,255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.ageAndGenderLabel = QtWidgets.QLabel(self.horizontalFrame_3)
        self.ageAndGenderLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.ageAndGenderLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ageAndGenderLabel.setStyleSheet("border: 1px solid rgb(88, 73, 255);\n"
"background-color: rgb(216, 227, 255);")
        self.ageAndGenderLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ageAndGenderLabel.setObjectName("ageAndGenderLabel")
        self.horizontalLayout_4.addWidget(self.ageAndGenderLabel)
        self.verticalLayout.addWidget(self.horizontalFrame_3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalFrame_5 = QtWidgets.QFrame(self.verticaBlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_5.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_5.setSizePolicy(sizePolicy)
        self.horizontalFrame_5.setMinimumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_5.setMaximumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_5.setStyleSheet("border-radius: 6px;")
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 25))
        self.label_6.setMaximumSize(QtCore.QSize(100, 25))
        self.label_6.setStyleSheet("background-color: rgb(51, 51, 255);\n"
"color: rgb(255,255,255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.addressLabel = QtWidgets.QLabel(self.horizontalFrame_5)
        self.addressLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.addressLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.addressLabel.setStyleSheet("border: 1px solid rgb(88, 73, 255);\n"
"background-color: rgb(216, 227, 255);")
        self.addressLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.addressLabel.setObjectName("addressLabel")
        self.horizontalLayout_6.addWidget(self.addressLabel)
        self.verticalLayout.addWidget(self.horizontalFrame_5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.verticaBlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_6.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_6.setSizePolicy(sizePolicy)
        self.horizontalFrame_6.setMinimumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_6.setMaximumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_6.setStyleSheet("border-radius: 6px;")
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 25))
        self.label_7.setMaximumSize(QtCore.QSize(100, 25))
        self.label_7.setStyleSheet("background-color: rgb(51, 51, 255);\n"
"color: rgb(255,255,255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.contactDetailsLabel = QtWidgets.QLabel(self.horizontalFrame_6)
        self.contactDetailsLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.contactDetailsLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.contactDetailsLabel.setStyleSheet("border: 1px solid rgb(88, 73, 255);\n"
"background-color: rgb(216, 227, 255);")
        self.contactDetailsLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.contactDetailsLabel.setObjectName("contactDetailsLabel")
        self.horizontalLayout_7.addWidget(self.contactDetailsLabel)
        self.verticalLayout.addWidget(self.horizontalFrame_6, 0, QtCore.Qt.AlignHCenter)
        self.horizontalFrame_7 = QtWidgets.QFrame(self.verticaBlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_7.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_7.setSizePolicy(sizePolicy)
        self.horizontalFrame_7.setMinimumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_7.setMaximumSize(QtCore.QSize(490, 50))
        self.horizontalFrame_7.setStyleSheet("border-radius: 6px;")
        self.horizontalFrame_7.setObjectName("horizontalFrame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalFrame_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.horizontalFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(100, 25))
        self.label_8.setMaximumSize(QtCore.QSize(100, 25))
        self.label_8.setStyleSheet("background-color: rgb(51, 51, 255);\n"
"color: rgb(255,255,255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.casesLabel = QtWidgets.QLabel(self.horizontalFrame_7)
        self.casesLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.casesLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.casesLabel.setStyleSheet("border: 1px solid rgb(88, 73, 255);\n"
"background-color: rgb(216, 227, 255);")
        self.casesLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.casesLabel.setObjectName("casesLabel")
        self.horizontalLayout_8.addWidget(self.casesLabel)
        self.verticalLayout.addWidget(self.horizontalFrame_7, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        detailsWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(detailsWindow)

        self.assignValues()

        QtCore.QMetaObject.connectSlotsByName(detailsWindow)

    def retranslateUi(self, detailsWindow):
        _translate = QtCore.QCoreApplication.translate
        detailsWindow.setWindowTitle(_translate("detailsWindow", "Details"))
        self.label_2.setText(_translate("detailsWindow", "Name"))
        self.nameLabel.setText(_translate("detailsWindow", "NULL"))
        self.label_3.setText(_translate("detailsWindow", "Criminal ID"))
        self.criminalIDLabel.setText(_translate("detailsWindow", "NULL"))
        self.label_4.setText(_translate("detailsWindow", "Age & Gender"))
        self.ageAndGenderLabel.setText(_translate("detailsWindow", "NULL"))
        self.label_6.setText(_translate("detailsWindow", "Address"))
        self.addressLabel.setText(_translate("detailsWindow", "NULL"))
        self.label_7.setText(_translate("detailsWindow", "Contact Details"))
        self.contactDetailsLabel.setText(_translate("detailsWindow", "NULL"))
        self.label_8.setText(_translate("detailsWindow", "Cases"))
        self.casesLabel.setText(_translate("detailsWindow", "NULL"))

import resources_rc
from PyQt5.QtGui import QPixmap

